theme: jekyll-theme-minimal
title: drowsyE's blog
description: personal archive
baseurl: ""
url: "https://drowsyE.github.io"
permalink: /:categories/:title/
timezone: Asia/Seoul
kramdown: 
  math_engine: mathjax